global:
  scrape_interval: 15s # 15 saniyede bir verileri çek

scrape_configs:
  - job_name: 'spring-boot-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8082'] # Docker'dan senin PC'ne erişim yolu